services:
  app:
    build:
      context: .
    environment:
      - BASE_URL
      - GLOBAL_SECRET
      - DB_DRIVERCLASSNAME
      - DB_PASSWORD
      - DB_URL
      - DB_USERNAME
      - INSTANCE_ID
      - NVD_API_KEY
      - PORT
      - REGION_ID
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.podman.internal:host-gateway"
  tester:
    build:
      context: .
      target: tester
    volumes:
      - ./src:/app/src:z
    command: ./mvnw clean test